codigoDefecto = 2
codigo2 = 12%
codigo3 = 14%

# Configuracion comun para todas las empresas
dirProcesando = C:\\monica11\\ComprobantesElectronicos\\Procesando
dirGenerado = C:\\monica11\\ComprobantesElectronicos\\Generados
dirPendienteSRI = C:\\monica11\\ComprobantesElectronicos\\PendientesSRI
dirErrores= C:\\monica11\\ComprobantesElectronicos\\Errores
#config propia de cada empresa

#config propia de cada empresa
#EMPRESA1
dirNoAutorizado1802129880001  =  C:\\monica11\\ComprobantesElectronicos\\NoAutorizados
dirAutorizados1802129880001 = C:\\monica11\\ComprobantesElectronicos\\Autorizados
dirLogo1802129880001  = C:\\monica11\\ComprobantesElectronicos\\logo6.jpg
dirFirma1802129880001  = C:\\monica11\\ComprobantesElectronicos\\firmaelectronica.p12
correoSiAutorizado1802129880001  = si
passFirma1802129880001  = G1802129880c
#servidorCorreo1802129880001 = smtp.office365.com
servidorCorreo1802129880001 = smtp.gmail.com
puertoCorreo1802129880001  = 587
correoRemitente1802129880001  = sumundonaturistasalto@gmail.com
correoPass1802129880001  = tqua opvj ebqs qeya
correoAsunto1802129880001  = Comprobante Electronico SU MUNDO NATURISTA respaldado por www.monicaecuador.com
dirIreport1802129880001  = C:\\monica11\\ComprobantesElectronicos\\IReport


agenteRetencion1802129880001 = No
regimen1802129880001 = GENERAL
